-- Zone positions for ALL body styles
-- Generated: 2026-02-18T05:06:29

-- sedan
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('sedan', 'engine_bay', 'Engine Bay', 46.3, 25.6, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 46.3, left_percent = 25.6;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('sedan', 'radiator', 'Radiator', 60.3, 15.0, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 60.3, left_percent = 15.0;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('sedan', 'front_left_wheel', 'Front Left Wheel', 68.0, 47.5, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 68.0, left_percent = 47.5;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('sedan', 'front_right_wheel', 'Front Right Wheel', 40.0, 15.1, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 40.0, left_percent = 15.1;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('sedan', 'rear_left_wheel', 'Rear Left Wheel', 50.6, 85.1, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 50.6, left_percent = 85.1;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('sedan', 'rear_right_wheel', 'Rear Right Wheel', 16.6, 50.4, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 16.6, left_percent = 50.4;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('sedan', 'cabin_interior', 'Cabin Interior', 31.5, 63.1, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 31.5, left_percent = 63.1;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('sedan', 'undercarriage_front', 'Front Undercarriage', 65.0, 25.0, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 65.0, left_percent = 25.0;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('sedan', 'undercarriage_rear', 'Rear Undercarriage', 61.1, 77.3, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 61.1, left_percent = 77.3;

-- mid_suv
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('mid_suv', 'engine_bay', 'Engine Bay', 46.2, 26.2, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 46.2, left_percent = 26.2;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('mid_suv', 'radiator', 'Radiator', 60.5, 16.3, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 60.5, left_percent = 16.3;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('mid_suv', 'front_left_wheel', 'Front Left Wheel', 72.1, 47.7, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 72.1, left_percent = 47.7;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('mid_suv', 'front_right_wheel', 'Front Right Wheel', 38.9, 11.7, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 38.9, left_percent = 11.7;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('mid_suv', 'rear_left_wheel', 'Rear Left Wheel', 53.2, 83.6, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 53.2, left_percent = 83.6;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('mid_suv', 'rear_right_wheel', 'Rear Right Wheel', 8.2, 53.1, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 8.2, left_percent = 53.1;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('mid_suv', 'cabin_interior', 'Cabin Interior', 35.0, 72.0, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 35.0, left_percent = 72.0;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('mid_suv', 'undercarriage_front', 'Front Undercarriage', 83.5, 27.6, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 83.5, left_percent = 27.6;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('mid_suv', 'undercarriage_rear', 'Rear Undercarriage', 64.0, 74.0, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 64.0, left_percent = 74.0;

-- full_suv
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('full_suv', 'engine_bay', 'Engine Bay', 44.7, 26.0, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 44.7, left_percent = 26.0;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('full_suv', 'radiator', 'Radiator', 58.6, 15.8, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 58.6, left_percent = 15.8;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('full_suv', 'front_left_wheel', 'Front Left Wheel', 68.7, 47.6, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 68.7, left_percent = 47.6;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('full_suv', 'front_right_wheel', 'Front Right Wheel', 39.6, 9.5, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 39.6, left_percent = 9.5;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('full_suv', 'rear_left_wheel', 'Rear Left Wheel', 54.9, 85.1, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 54.9, left_percent = 85.1;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('full_suv', 'rear_right_wheel', 'Rear Right Wheel', 11.8, 53.9, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 11.8, left_percent = 53.9;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('full_suv', 'cabin_interior', 'Cabin Interior', 31.7, 62.1, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 31.7, left_percent = 62.1;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('full_suv', 'undercarriage_front', 'Front Undercarriage', 79.6, 34.2, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 79.6, left_percent = 34.2;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('full_suv', 'undercarriage_rear', 'Rear Undercarriage', 63.1, 75.7, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 63.1, left_percent = 75.7;

-- mid_truck
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('mid_truck', 'engine_bay', 'Engine Bay', 40.8, 24.1, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 40.8, left_percent = 24.1;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('mid_truck', 'radiator', 'Radiator', 54.3, 15.4, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 54.3, left_percent = 15.4;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('mid_truck', 'front_left_wheel', 'Front Left Wheel', 68.9, 44.6, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 68.9, left_percent = 44.6;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('mid_truck', 'front_right_wheel', 'Front Right Wheel', 39.6, 11.9, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 39.6, left_percent = 11.9;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('mid_truck', 'rear_left_wheel', 'Rear Left Wheel', 52.4, 85.1, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 52.4, left_percent = 85.1;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('mid_truck', 'rear_right_wheel', 'Rear Right Wheel', 65.0, 60.0, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 65.0, left_percent = 60.0;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('mid_truck', 'cabin_interior', 'Cabin Interior', 28.9, 57.6, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 28.9, left_percent = 57.6;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('mid_truck', 'undercarriage_front', 'Front Undercarriage', 78.2, 26.1, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 78.2, left_percent = 26.1;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('mid_truck', 'undercarriage_rear', 'Rear Undercarriage', 57.5, 75.3, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 57.5, left_percent = 75.3;

-- full_truck
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('full_truck', 'engine_bay', 'Engine Bay', 40.5, 26.2, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 40.5, left_percent = 26.2;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('full_truck', 'radiator', 'Radiator', 55.5, 15.1, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 55.5, left_percent = 15.1;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('full_truck', 'front_left_wheel', 'Front Left Wheel', 69.4, 44.3, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 69.4, left_percent = 44.3;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('full_truck', 'front_right_wheel', 'Front Right Wheel', 36.6, 8.6, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 36.6, left_percent = 8.6;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('full_truck', 'rear_left_wheel', 'Rear Left Wheel', 53.0, 86.9, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 53.0, left_percent = 86.9;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('full_truck', 'rear_right_wheel', 'Rear Right Wheel', 11.5, 58.2, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 11.5, left_percent = 58.2;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('full_truck', 'cabin_interior', 'Cabin Interior', 28.7, 57.9, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 28.7, left_percent = 57.9;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('full_truck', 'undercarriage_front', 'Front Undercarriage', 78.8, 26.5, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 78.8, left_percent = 26.5;
INSERT INTO vehicle_zones (body_style, zone_name, zone_label, top_percent, left_percent, size_px) VALUES ('full_truck', 'undercarriage_rear', 'Rear Undercarriage', 59.4, 76.3, 80) ON CONFLICT (body_style, zone_name) DO UPDATE SET top_percent = 59.4, left_percent = 76.3;
